### ISSUE TITLE
Request updates

### ISSUE THREAD

**Issue by u3u** [yuki540net/dotfiles#1]
<img src="https://user-images.githubusercontent.com/20062482/42076258-f53b91ea-7ba6-11e8-9125-7da4df142fe9.png" width="150">

I want to use the same configuration as yui (๑>◡<๑)
If you can also share the `settings.json` of `vscode`, it would be better!

**Comment by yui540** [comment]
英語話せないので、日本語でごめんなさい🙇‍♂️

vscodeをこれから使い始めるので、開発環境が整ったら公開しますので、もう少しお待ちください🙇‍♂️

**Comment by u3u** [comment]
私は英語と日本語のどちらも話せないので、すみません、私はGoogleを通して翻訳しています。 投稿ビデオでvscodeを見たので、あなたがそれを使用しないと、私が言ったことを無視することができます。😄
しかし、あなたのvimとzshが変更されている場合は、それを更新してください。🙏

翻訳されたテキストが人々に不快感を与えるかどうかはわかりません。 はいの場合は、ご理解ください！

**Comment by yui540** [comment]
今のところ.vimrc, .zshrcは変更してません☀️
変更があった時は、随時更新していきますね🙏

**Comment by u3u** [comment]
OK、ありがとう！！
